/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CasesRouteRouteImport } from './routes/cases/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesProductWalltimeRouteImport } from './routes/cases/product/walltime'
import { Route as CasesProductTestRouteImport } from './routes/cases/product/test'
import { Route as CasesProductRicsRouteImport } from './routes/cases/product/rics'
import { Route as CasesProductCoindetRouteImport } from './routes/cases/product/coindet'
import { Route as CasesProductAthayogaRouteImport } from './routes/cases/product/athayoga'
import { Route as CasesGameAtomv2RouteImport } from './routes/cases/game/atomv2'
import { Route as CasesGameAtomv1RouteImport } from './routes/cases/game/atomv1'

const CasesRouteRoute = CasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductWalltimeRoute = CasesProductWalltimeRouteImport.update({
  id: '/product/walltime',
  path: '/product/walltime',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductTestRoute = CasesProductTestRouteImport.update({
  id: '/product/test',
  path: '/product/test',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductRicsRoute = CasesProductRicsRouteImport.update({
  id: '/product/rics',
  path: '/product/rics',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductCoindetRoute = CasesProductCoindetRouteImport.update({
  id: '/product/coindet',
  path: '/product/coindet',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesProductAthayogaRoute = CasesProductAthayogaRouteImport.update({
  id: '/product/athayoga',
  path: '/product/athayoga',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesGameAtomv2Route = CasesGameAtomv2RouteImport.update({
  id: '/game/atomv2',
  path: '/game/atomv2',
  getParentRoute: () => CasesRouteRoute,
} as any)
const CasesGameAtomv1Route = CasesGameAtomv1RouteImport.update({
  id: '/game/atomv1',
  path: '/game/atomv1',
  getParentRoute: () => CasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/game/atomv1': typeof CasesGameAtomv1Route
  '/cases/game/atomv2': typeof CasesGameAtomv2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/coindet': typeof CasesProductCoindetRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/test': typeof CasesProductTestRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesIndexRoute
  '/cases/game/atomv1': typeof CasesGameAtomv1Route
  '/cases/game/atomv2': typeof CasesGameAtomv2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/coindet': typeof CasesProductCoindetRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/test': typeof CasesProductTestRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteRouteWithChildren
  '/cases/': typeof CasesIndexRoute
  '/cases/game/atomv1': typeof CasesGameAtomv1Route
  '/cases/game/atomv2': typeof CasesGameAtomv2Route
  '/cases/product/athayoga': typeof CasesProductAthayogaRoute
  '/cases/product/coindet': typeof CasesProductCoindetRoute
  '/cases/product/rics': typeof CasesProductRicsRoute
  '/cases/product/test': typeof CasesProductTestRoute
  '/cases/product/walltime': typeof CasesProductWalltimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/cases/'
    | '/cases/game/atomv1'
    | '/cases/game/atomv2'
    | '/cases/product/athayoga'
    | '/cases/product/coindet'
    | '/cases/product/rics'
    | '/cases/product/test'
    | '/cases/product/walltime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/cases/game/atomv1'
    | '/cases/game/atomv2'
    | '/cases/product/athayoga'
    | '/cases/product/coindet'
    | '/cases/product/rics'
    | '/cases/product/test'
    | '/cases/product/walltime'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/cases/'
    | '/cases/game/atomv1'
    | '/cases/game/atomv2'
    | '/cases/product/athayoga'
    | '/cases/product/coindet'
    | '/cases/product/rics'
    | '/cases/product/test'
    | '/cases/product/walltime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRouteRoute: typeof CasesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/walltime': {
      id: '/cases/product/walltime'
      path: '/product/walltime'
      fullPath: '/cases/product/walltime'
      preLoaderRoute: typeof CasesProductWalltimeRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/test': {
      id: '/cases/product/test'
      path: '/product/test'
      fullPath: '/cases/product/test'
      preLoaderRoute: typeof CasesProductTestRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/rics': {
      id: '/cases/product/rics'
      path: '/product/rics'
      fullPath: '/cases/product/rics'
      preLoaderRoute: typeof CasesProductRicsRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/coindet': {
      id: '/cases/product/coindet'
      path: '/product/coindet'
      fullPath: '/cases/product/coindet'
      preLoaderRoute: typeof CasesProductCoindetRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/product/athayoga': {
      id: '/cases/product/athayoga'
      path: '/product/athayoga'
      fullPath: '/cases/product/athayoga'
      preLoaderRoute: typeof CasesProductAthayogaRouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/game/atomv2': {
      id: '/cases/game/atomv2'
      path: '/game/atomv2'
      fullPath: '/cases/game/atomv2'
      preLoaderRoute: typeof CasesGameAtomv2RouteImport
      parentRoute: typeof CasesRouteRoute
    }
    '/cases/game/atomv1': {
      id: '/cases/game/atomv1'
      path: '/game/atomv1'
      fullPath: '/cases/game/atomv1'
      preLoaderRoute: typeof CasesGameAtomv1RouteImport
      parentRoute: typeof CasesRouteRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/cases/route' {
  const createFileRoute: CreateFileRoute<
    '/cases',
    FileRoutesByPath['/cases']['parentRoute'],
    FileRoutesByPath['/cases']['id'],
    FileRoutesByPath['/cases']['path'],
    FileRoutesByPath['/cases']['fullPath']
  >
}
declare module './routes/cases/index' {
  const createFileRoute: CreateFileRoute<
    '/cases/',
    FileRoutesByPath['/cases/']['parentRoute'],
    FileRoutesByPath['/cases/']['id'],
    FileRoutesByPath['/cases/']['path'],
    FileRoutesByPath['/cases/']['fullPath']
  >
}
declare module './routes/cases/game/atomv1' {
  const createFileRoute: CreateFileRoute<
    '/cases/game/atomv1',
    FileRoutesByPath['/cases/game/atomv1']['parentRoute'],
    FileRoutesByPath['/cases/game/atomv1']['id'],
    FileRoutesByPath['/cases/game/atomv1']['path'],
    FileRoutesByPath['/cases/game/atomv1']['fullPath']
  >
}
declare module './routes/cases/game/atomv2' {
  const createFileRoute: CreateFileRoute<
    '/cases/game/atomv2',
    FileRoutesByPath['/cases/game/atomv2']['parentRoute'],
    FileRoutesByPath['/cases/game/atomv2']['id'],
    FileRoutesByPath['/cases/game/atomv2']['path'],
    FileRoutesByPath['/cases/game/atomv2']['fullPath']
  >
}
declare module './routes/cases/product/athayoga' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/athayoga',
    FileRoutesByPath['/cases/product/athayoga']['parentRoute'],
    FileRoutesByPath['/cases/product/athayoga']['id'],
    FileRoutesByPath['/cases/product/athayoga']['path'],
    FileRoutesByPath['/cases/product/athayoga']['fullPath']
  >
}
declare module './routes/cases/product/coindet' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/coindet',
    FileRoutesByPath['/cases/product/coindet']['parentRoute'],
    FileRoutesByPath['/cases/product/coindet']['id'],
    FileRoutesByPath['/cases/product/coindet']['path'],
    FileRoutesByPath['/cases/product/coindet']['fullPath']
  >
}
declare module './routes/cases/product/rics' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/rics',
    FileRoutesByPath['/cases/product/rics']['parentRoute'],
    FileRoutesByPath['/cases/product/rics']['id'],
    FileRoutesByPath['/cases/product/rics']['path'],
    FileRoutesByPath['/cases/product/rics']['fullPath']
  >
}
declare module './routes/cases/product/test' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/test',
    FileRoutesByPath['/cases/product/test']['parentRoute'],
    FileRoutesByPath['/cases/product/test']['id'],
    FileRoutesByPath['/cases/product/test']['path'],
    FileRoutesByPath['/cases/product/test']['fullPath']
  >
}
declare module './routes/cases/product/walltime' {
  const createFileRoute: CreateFileRoute<
    '/cases/product/walltime',
    FileRoutesByPath['/cases/product/walltime']['parentRoute'],
    FileRoutesByPath['/cases/product/walltime']['id'],
    FileRoutesByPath['/cases/product/walltime']['path'],
    FileRoutesByPath['/cases/product/walltime']['fullPath']
  >
}

interface CasesRouteRouteChildren {
  CasesIndexRoute: typeof CasesIndexRoute
  CasesGameAtomv1Route: typeof CasesGameAtomv1Route
  CasesGameAtomv2Route: typeof CasesGameAtomv2Route
  CasesProductAthayogaRoute: typeof CasesProductAthayogaRoute
  CasesProductCoindetRoute: typeof CasesProductCoindetRoute
  CasesProductRicsRoute: typeof CasesProductRicsRoute
  CasesProductTestRoute: typeof CasesProductTestRoute
  CasesProductWalltimeRoute: typeof CasesProductWalltimeRoute
}

const CasesRouteRouteChildren: CasesRouteRouteChildren = {
  CasesIndexRoute: CasesIndexRoute,
  CasesGameAtomv1Route: CasesGameAtomv1Route,
  CasesGameAtomv2Route: CasesGameAtomv2Route,
  CasesProductAthayogaRoute: CasesProductAthayogaRoute,
  CasesProductCoindetRoute: CasesProductCoindetRoute,
  CasesProductRicsRoute: CasesProductRicsRoute,
  CasesProductTestRoute: CasesProductTestRoute,
  CasesProductWalltimeRoute: CasesProductWalltimeRoute,
}

const CasesRouteRouteWithChildren = CasesRouteRoute._addFileChildren(
  CasesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRouteRoute: CasesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
